advertising.advertising_entity.*:
  type: config_entity
  label: 'Advertising entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    ID:
      type: number
      label: ' id the advertising'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    address:
      type: url
      label: 'url'
    select:
      type: string
      label: 'select place'
    breakpoints:
      type: string
      label: 'Breakpoints' 


