advertising.advertising_entity.*:
  type: config_entity
  label: 'Advertising entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    url:
      type: string
      label: 'url'
    place_select:
      type: string
      label: 'place'
    breakpoints:
      type: string
      label: 'Breakpoints' 


